
const AUTH_MESSAGES = require("../constants/messages/authMessages");
const asyncHandler = require("../utils/asyncHandlers");
const authService=require("../services/authService");
const { getLinkedInUser } = require("../services/linkedInService");
const generateUniqueUsername = require("../utils/auth/generateUniqueUsername");
const User = require("../models/User");

const registerUser=asyncHandler(async(req,res)=>{
    const user=await authService.registerUser(req.body);
    return res.status(201).json({
        success:true,
        message:AUTH_MESSAGES.USER_REGISTERED,
        data:user
    });
    
});

const verifyEmail=asyncHandler(async(req,res,next)=>{
        const result=await authService.verifyEmail(req.query.token);
        return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.EMAIL_VERIFIED_SUCCESS,
        data:result
    });

});

const loginUser=asyncHandler(async(req,res,next)=>{
    const result=await authService.loginUser(req.body);
    res.cookie("refreshToken", result.refreshToken, {
        httpOnly: true,
        secure: process.env.NODE_ENV === "production",
        sameSite: "strict",
        maxAge: 30 * 24 * 60 * 60 * 1000
    });
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.LOGIN_SUCCESS,
        data:{ user: result.user,
            accessToken: result.accessToken,
        needsOnboarding: result.needsOnboarding}
    });
});

const googleLogin = asyncHandler(async (req, res, next) => {
    const result = await authService.googleLogin(req.user);

    const { accessToken, refreshToken } = result;

    const redirectUrl =
        `${process.env.CLIENT_URL}/oauth-success` +
        `?accessToken=${encodeURIComponent(accessToken)}` +
        `&refreshToken=${encodeURIComponent(refreshToken)}`;

    return res.redirect(redirectUrl);
});
const linkedinLogin = asyncHandler(async (req, res) => {
    const { code } = req.query;

    if (!code) {
        return res.status(400).json({
            success: false,
            message: "LinkedIn authorization code is missing"
        });
    }

    const profile = await getLinkedInUser(code);

    const email = profile.email?.toLowerCase();

    if (!email) {
        return res.status(400).json({
            success: false,
            message: "LinkedIn account does not have an email"
        });
    }

    let user = await User.findOne({ email });

    if (user?.isDeleted) {
        return res.status(403).json({
            success: false,
            message: AUTH_MESSAGES.ACCOUNT_DELETED
        });
    }

    if (!user) {
        const username = await generateUniqueUsername(
            profile.name || "linkedin_user",
            email
        );

        user = await User.create({
            name: profile.name,
            username,
            email,
            password: null,
            profilePicture: profile.picture || "",
            isVerified: true,
            isActive: true,
            authProvider: "linkedin",
            providerId: profile.sub
        });
    }

    const result = await authService.linkedinLogin(user);

    // Get tokens generated by the service
    const { accessToken, refreshToken } = result;

    // Redirect to React
    const redirectUrl =
        `${process.env.CLIENT_URL}/oauth-success` +
        `?accessToken=${encodeURIComponent(accessToken)}` +
        `&refreshToken=${encodeURIComponent(refreshToken)}`;

    return res.redirect(redirectUrl);
});
const refreshToken=asyncHandler(async(req,res)=>{
    const {refreshToken}=req.body;
    const result=await authService.refreshToken(refreshToken);
    res.cookie("refreshToken", result.refreshToken, {
        httpOnly: true,
        secure: process.env.NODE_ENV === "production",
        sameSite: "strict",
        maxAge: 30 * 24 * 60 * 60 * 1000
    });
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.ACCESS_TOKEN_REFRESHED,
        data:result
    });
});

const logout=asyncHandler(async(req,res)=>{
    await authService.logout(req.cookies.refreshToken);
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.LOGOUT_SUCCESS
    });
})

const logoutAll = asyncHandler(async (req, res) => {

    await authService.logoutAll(req.user.id);

    return res.status(200).json({
        success: true,
        message: AUTH_MESSAGES.LOGOUT_ALL_SUCCESS
    });
});

const forgotPassword= asyncHandler(async(req,res)=>{
    const {email}=req.body;
   await authService.forgotPassword(email);
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.PASSWORD_RESET_EMAIL_SENT
    })
});

const resetPassword=asyncHandler(async(req,res)=>{
    await authService.resetPassword(req.body);
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.PASSWORD_RESET_SUCCESS
    });
});

const changePassword=asyncHandler(async(req,res)=>{
    await authService.changePassword(req.user.id,req.body);
    return res.status(200).json({
        success:true,
        message:AUTH_MESSAGES.CHANGE_PASSWORD_SUCCESS
    });
});

const getCurrentUser = asyncHandler(async (req, res) => {
    const user = await authService.getCurrentUser(req.user.id);

    return res.status(200).json({
        success: true,
        message: AUTH_MESSAGES.CURRENT_USER_FETCHED,
        data: user
    });
});

const updateProfile = asyncHandler(async (req, res) => {
    const user = await authService.updateProfile(
        req.user.id,
        req.body
    );

    return res.status(200).json({
        success: true,
        message: AUTH_MESSAGES.PROFILE_UPDATED_SUCCESS,
        data: user
    });
});
const deleteAccount = asyncHandler(async (req, res) => {
    await authService.deleteAccount(
        req.user.id,
        req.body.password
    );

    return res.status(200).json({
        success: true,
        message: AUTH_MESSAGES.ACCOUNT_DELETED
    });
});

const resendVerificationEmail=asyncHandler(async(req,res)=>{
    const {email}=req.body;
   await authService.resendVerificationEmail(email);
   return res.status(200).json({
    success:true,
    message:AUTH_MESSAGES.VERIFICATION_EMAIL_SENT
   })
});


module.exports={registerUser,verifyEmail,loginUser,refreshToken,logout,logoutAll,forgotPassword,resetPassword,changePassword
    ,getCurrentUser,updateProfile,deleteAccount,resendVerificationEmail, googleLogin,linkedinLogin};